import Head from 'next/head';
import type { NextPage } from 'next';
import type { AppProps } from 'next/app';

const MyApp:NextPage<AppProps> = ({ Component, pageProps }) => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {/* eslint-disable-next-line react/jsx-props-no-spreading */}
    <Component {...pageProps} />
  </>
);

export default MyApp;
